# Emacs-style line motions 
Set-PSReadLineKeyHandler -Key Ctrl+a -Function BeginningOfLine
Set-PSReadLineKeyHandler -Key Ctrl+e -Function EndOfLine
Set-PSReadLineKeyHandler -Chord Ctrl+f -Function ForwardChar
Set-PSReadLineKeyHandler -Chord Ctrl+b -Function BackwardChar

# Emacs-style line editing keybindings
Set-PSReadLineKeyHandler -Key Ctrl+u -Function BackwardKillLine
Set-PSReadLineKeyHandler -Key Ctrl+w -Function BackwardKillWord
Set-PSReadLineKeyHandler -Key Ctrl+k -Function KillLine
# Below mimics bash's Ctrl+d, generated by Claude AI
Set-PSReadLineKeyHandler -Chord Ctrl+d -ScriptBlock {
    param($key, $arg)
    
    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    
    if ($line.Length -eq 0) {
        # Line is empty, exit the shell
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert('exit')
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
    }
    else {
        # Line has content, delete character forward
        [Microsoft.PowerShell.PSConsoleReadLine]::DeleteChar($key, $arg)
    }
}
#Set-PSReadLineKeyHandler -Chord Ctrl+d -Function DeleteChar

# Bash-style history navigation
Set-PSReadLineKeyHandler -Chord Ctrl+p -Function PreviousHistory
Set-PSReadLineKeyHandler -Chord Ctrl+n -Function NextHistory

